### ISSUE TITLE
License

### ISSUE THREAD

**Issue by neupanedipen** [powerpoint45/dtube-mobile-unofficial#12]
Is the project open source? Please add license to the repository.

**Comment by IzzySoft** [comment]
Not yet decided on the license?

**Comment by powerpoint45** [comment]
I have not decided quite yet. Please allow some time. Thank you!

**Comment by IzzySoft** [comment]
If you need some assistance (pros/cons or which license(s) might be preferable), just say so. I'm sure there's someone who can help.

**Comment by IzzySoft** [comment]
Any news, @powerpoint45? It's almost a year now, come on 😃

**Comment by powerpoint45** [comment]
Added License
#14

**Comment by IzzySoft** [comment]
Thanks a lot! :+1:
