### ISSUE TITLE
No feedback on login attemp

### ISSUE THREAD

**Issue by hoschi-it** [powerpoint45/dtube-mobile-unofficial#13]
Hello!

Device: Android 6.0.1, No Google Services

What I did:

- Installed app from apk
- opened app
- Menu > Login
- Filled in
   - username
   - private posting key
- enabled app upvote
- enabled following
- pressed login

What happens - Problem:
- Page refreshes (checkboxes turn white and the red again)
- input fields remain filled out
- nothing else

**Comment by powerpoint45** [comment]
Thanks for the report! I have added a toast message when the login fails.
