### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by 2relativ** [powerpoint45/dtube-mobile-unofficial#3]
Hi there,

I don't know for which reason it isn't working but I don't see any videos and i can't login. However the app has a nice design. I hope you can fix this and I am available for beta version for testing. Here are some informations that may help you: 
I am from Germany and may smartphone is a Motorola Moto X Play (Lux) running LineageOS 14.1-20171228-Nightly-Lux (Android 7.1.2) with safety updates till December 2017 and MagiskSU for Root.

**Comment by powerpoint45** [comment]
Thanks. Ya Steemit updated their api calls and caused problems for this app. I am currently working on fixing these issues.

**Comment by k0d3g3ar** [comment]
Same results as 2relativ here.  I'm trying to run this on an Android 10" Tablet and also on my Nvidia Shield Android TV.  Neither work, but seems that you are already aware of that.  However one additional thing....  On an Android TV (which is the ideal environment to use this), it is not responding at all to the remote control that moves the selected button forward/backwards.  I am not sure how that is coded or what can be done, but its a deal breaker if the app doesn't support a remote control like that.  My guess is that it reacts to the same input trigger as pressing the TAB key or forward/backward arrow to move focus onto the next button, etc.  If you can get that to work, and to scroll as a result of using the remote to move the screen around, you have a winner here.

**Comment by powerpoint45** [comment]
Fixed! Check releases: https://github.com/powerpoint45/dtube-mobile-unofficial/releases 
Feel free to open up another issue if you notice anything.
