### ISSUE TITLE
No Video plays

### ISSUE THREAD

**Issue by TssT16** [powerpoint45/dtube-mobile-unofficial#4]
Hi
first of all a realy nice looking app.
I have a rooted Nexus 5 with cyanogen-Mod-version: 13.0-20161108-NIGHTLY-hammerhead
Android-version: 6.0.1

My problem is when I click on a video the text shows up: "no compatible source was found for this media."

Have I a to old android version or must I install something extra ?

Another question could you also programming a app for https://dsound.audio ?

**Comment by powerpoint45** [comment]
Hi! Please try installing the latest release again and let me know. https://github.com/powerpoint45/dtube-mobile-unofficial/releases I recently edited the release apk. Does it do this with every single video?

I could look into developing a dsound app as well in the future.

**Comment by TssT16** [comment]
Yes it is by every single video without pressing the play button.

I reinstalled the latest release 1.1 that has nothing changed.

**Comment by powerpoint45** [comment]
Just for the heck of it, would you mind loading the dtube website on your phone and try playing a video on the website just to insure it's a specific issue with my implementation.Just let me know if you can get a video to load on your phone on the dtube website.

**Comment by TssT16** [comment]
Yes that works, only by videos bigger than approximately 15min is  it not working.

**Comment by k0d3g3ar** [comment]
Suggestion... Before you consider spending time working on a DSound app, can you get this to work on Android TV devices?  It doesn't work at all, and doesn't recognize the remote control.  Thanks.

**Comment by powerpoint45** [comment]
@TssT16 But on the app, even videos under 15 mins won't work right?

**Comment by powerpoint45** [comment]
@k0d3g3ar Ya I will

**Comment by TssT16** [comment]
@powerpoint45 yes

**Comment by powerpoint45** [comment]
Please try out the latest release. Should be fixed: https://github.com/powerpoint45/dtube-mobile-unofficial/releases

If you are still having issues feel free to re-open a bug report
