### ISSUE TITLE
QR-Code not workong

### ISSUE THREAD

**Issue by hiFloh** [powerpoint45/dtube-mobile-unofficial#5]
I have installed version 1.1 of this app and tried to sacan the QR-Code but there showde only a white screen.
I have a Samsung Galaxy S7 with Android 7.0

**Comment by powerpoint45** [comment]
Before you scanned the qr code did you make sure that you pressed "show private key" before clicking the qr code to make it fullscreen before you use the camera to scan it? If you do not press "show private screen" it will give you a qrcode with a fake password.

Also could you go into more detail as to what exactly happens the moment after you scan the code. For example, do you see anything on the screen or is it only a white screen with nothing on it?

**Comment by powerpoint45** [comment]
Issue Identified and fixed. Was a permissions issue. See https://github.com/powerpoint45/dtube-mobile-unofficial/commit/5dfff68ef7ad2cde9fdae8064c1b0fd087c12c7f

Get the latest *fixed release here: https://github.com/powerpoint45/dtube-mobile-unofficial/blob/master/app/release/app-release.apk

**Comment by hiFloh** [comment]
I have to appologize me for not answering, but I havent't noticed that you have answerd.
Beside the Issue you managed to find. I also forgott to press "show private key".
Thanks for the response
