### ISSUE TITLE
Not designed or tested for any device other than a simple phone

### ISSUE THREAD

**Issue by k0d3g3ar** [powerpoint45/dtube-mobile-unofficial#6]
The application (latest release as of 1/24/18) does work now, and does show content.  But the design & testing appears to have only been done on a phone.  Android devices include tablets and Android TV (the latter being the most relevant to DTube).  In the case of larger screen devices, the content doesn't provide a thumbnail on the device that doesn't take up the entire screen width.  The application needs to be able to recognize the device that its being run on, and resize its screen and support input devices, appropriate to that device.  It is basically useless on an Android TV because of the design (see photo of it on my NVidia Shield TV):

![selection_806](https://user-images.githubusercontent.com/457291/35348583-ac120eda-00f5-11e8-9b28-bad5fb75fd6c.jpg)

Additionally, the control device on an Android TV isn't supported correctly.  The user should be able to use any remote control that advances between the buttons on the page, to select content and play it.  The remote control on an Android TV is not recognized at all.   The only button that works is to go "back" which just quits the application.

**Comment by powerpoint45** [comment]
This is something I will be working on. App was designed primarily for a phone. need to get myself an android TV stick to start implementation for a TV.

**Comment by k0d3g3ar** [comment]
Where are you located?  I can send you a typical Android TV device to work on if you like.

**Comment by powerpoint45** [comment]
Oh hey that would be sweet! I live in Texas. I can give you the exact location over email or discord.
Email: removed
Discord for this project: https://discord.gg/3h88GDb

**Comment by k0d3g3ar** [comment]
You got it.  Just sent you an email to get the details.

**Comment by powerpoint45** [comment]
Got it! Thanks so much. Would love to work on getting it compatible on these Android TV devices.

**Comment by powerpoint45** [comment]
Just an update. I am VERY close to finishing basic integration with Android TV. it should not be much longer till I'm finished. Thanks for your patience

https://d.tube/#!/v/immawake/upgymmuj

**Comment by powerpoint45** [comment]
This app now fully works with Android TV

See latest release: https://github.com/powerpoint45/dtube-mobile-unofficial/releases
